#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

allownonascii=$(git config hooks.allownonascii)

exec 1>&2

if [ "$allownonascii" != "true" ] &&
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

ASTYLE=astyle
ASTYLE_PARAMETERS="--options=tool/astyle/options"
files=`git-diff-index --diff-filter=ACMR --name-only -r --cached $against --`

echo "Applying make-up..."
for file in $files; do
    x=`echo $file |grep -E '(\.cpp|\.hpp)'`
    if test "x$x" != "x"; then
        $ASTYLE ${ASTYLE_PARAMETERS} $file
        git add $file
    fi
done
echo "She's all set."
