find_library( protocol_STATIC_LIBRARY libprotocol.a HINTS "${PROJECT_SOURCE_DIR}/dependency/protocol/distribution/library" )
find_library( protocol_SHARED_LIBRARY NAMES libprotocol.so libprotocol.dylib HINTS "${PROJECT_SOURCE_DIR}/dependency/protocol/distribution/library" )
find_path( protocol_INCLUDE "corvusoft/protocol/frame.hpp" HINTS "${PROJECT_SOURCE_DIR}/dependency/protocol/distribution/include" )

if ( protocol_INCLUDE AND protocol_STATIC_LIBRARY AND protocol_SHARED_LIBRARY )
    set( PROTOCOL_FOUND TRUE )
    message( STATUS "Located Protocol include at: ${protocol_INCLUDE}" )
    message( STATUS "Located Protocol static library at: ${protocol_STATIC_LIBRARY}" )
    message( STATUS "Located Protocol shared library at: ${protocol_SHARED_LIBRARY}" )
else ( )
    message( FATAL_ERROR "Failed to locate Protocol dependency, try again after performing: mkdir build; cd build; cmake ..; make install" )
endif ( )
